version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: boards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/env.local
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/boards_db?schema=public
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - uploads_data:/app/uploads
    command: sh -c "npm run db:migrate && npm run db:seed && npm start"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:4000/api
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  uploads_data:
